name: build
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    paths:
      - "go.mod"
      - "**.go"
      - "Makefile"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.24.0'
permissions:
  contents: read
jobs:
  build_netctl:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Download Dependencies
        run: go mod download
      - name: Install libvirt
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-dev
      - name: Build Binaries
        run: |
          make build
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: netctl_binaries
          path: _output/binaries